import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/theme";
import { ClerkProvider } from "@clerk/nextjs";
import { connectMongoDB } from "@/config/mongodb";
import CustomLayout from "@/custom-layout";


export const metadata: Metadata = {
  title: "Your Safe Mind",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  await connectMongoDB()
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        >
          <ThemeProvider>
            <CustomLayout>
        {children}
        </CustomLayout>
        </ThemeProvider>
      </body>
    </html>
        </ClerkProvider>
  );
}
